# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-04-11 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='conf.Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='factura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='conf.Factura'),
            preserve_default=False,
        ),
    ]
