# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-04-11 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0002_auto_20190411_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
