# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-04-11 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0003_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_compra',
            field=models.DateField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
