# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-04-11 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0004_auto_20190411_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_compra',
        ),
        migrations.AddField(
            model_name='factura',
            name='factura1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='factura2',
            field=models.IntegerField(null=True),
        ),
    ]
